[theme]
primaryColor = "#3F51B5"
backgroundColor = "#FAFAFA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#212121"
font = "sans serif"

[server]
headless = true
runOnSave = false

[browser]
gatherUsageStats = false
